use dbms_insurance_schema;

CREATE TABLE IF NOT EXISTS T2_CUSTOMER (
	T2_Cust_Id VARCHAR(20) NOT NULL, 
    T2_Cust_FName VARCHAR(10) NOT NULL, 
    T2_Cust_LName VARCHAR(10) NOT NULL, 
    T2_Cust_DOB DATE NOT NULL,
    T2_Cust_Gender VARCHAR(2) NOT NULL, 
    T2_Cust_Address VARCHAR(20) NOT NULL, 
    T2_Cust_MOB_Number DECIMAL(10, 0) NOT NULL, 
    T2_Cust_Email VARCHAR(30) NULL, 
    T2_Cust_PassportNumber VARCHAR(20) NULL, 
    T2_Cust_Marital_Status VARCHAR(8) NULL,
	T2_Cust_PPS_Number INT NULL,
    CONSTRAINT T2_PK_CUSTOMER PRIMARY KEY (T2_Cust_Id)
); 

CREATE TABLE IF NOT EXISTS T2_APPLICATION(
    T2_Application_Id VARCHAR(20) NOT NULL, 
    T2_Cust_Id VARCHAR(20) NOT NULL, 
    T2_Vehicle_Id VARCHAR(20) NULL,
    T2_Application_Status CHAR NOT NULL, 
    T2_Coverage VARCHAR(50),
    CONSTRAINT T2_PK_APPLICATION PRIMARY KEY (T2_Application_Id),
    CONSTRAINT T2_FK_APPLICATION FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id) 
);

CREATE TABLE IF NOT EXISTS T2_QUOTE(
	T2_Quote_Id VARCHAR(20) NOT NULL,
	T2_Application_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Issue_Date DATE NOT NULL,
	T2_Valid_From_Date DATE NOT NULL,
	T2_Valid_Till_Date DATE NOT NULL,
	T2_Description VARCHAR(100) NOT NULL,
	T2_Product_Id VARCHAR(20) NULL,
	T2_Coverage_Level VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_QUOTE PRIMARY KEY(T2_Quote_Id),
    CONSTRAINT T2_FK_CUST_QUOTE FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_APP_QUOTE FOREIGN KEY (T2_Application_Id) REFERENCES T2_APPLICATION(T2_Application_Id)
);

CREATE TABLE IF NOT EXISTS T2_INSURANCE_POLICY(
	T2_Agreement_Id VARCHAR(20) NOT NULL,
	T2_Application_Id VARCHAR(20)  NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Department_Name VARCHAR(20) NULL,
	T2_Policy_Number VARCHAR(20) NULL,
	T2_Start_Date DATE NOT NULL,
	T2_Expiry_Date DATE NOT NULL,
	T2_Term_Condition_Description VARCHAR(100) NOT NULL,
	CONSTRAINT T2_PK_INSURANCE_POLICY PRIMARY KEY(T2_Agreement_Id),
    CONSTRAINT T2_FK_CUST_INSURANCE_POLICY FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_APP_INSURANCE_POLICY FOREIGN KEY (T2_Application_Id) REFERENCES T2_APPLICATION(T2_Application_Id)
);

CREATE TABLE IF NOT EXISTS T2_PREMIUM_PAYMENT(
	T2_Premium_Payment_Id VARCHAR(20) NOT NULL, 
	T2_Policy_Number VARCHAR(20) NOT NULL,
	T2_Premium_Payment_Amount INTEGER NOT NULL, 
	T2_Premium_Payment_Schedule DATE NOT NULL, 
	T2_Receipt_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_PREMIUM_PAYMENT PRIMARY KEY(T2_Premium_Payment_Id, T2_Cust_Id),
    CONSTRAINT T2_FK_PREMIUM_PAYMENT FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id)
);

CREATE TABLE IF NOT EXISTS T2_VEHICLE(
	T2_Vehicle_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Policy_Id VARCHAR(20) NOT NULL,
	T2_Dependent_Nok_Id VARCHAR(20) NOT NULL,
	T2_Vehicle_Registration_Number VARCHAR(20) NOT NULL,
	T2_Vehicle_Value INTEGER NULL,
	T2_Vehicle_Type VARCHAR(20) NOT NULL,
	T2_Vehicle_Size INTEGER NULL,
	T2_Vehicle_Number_Of_Seat INTEGER NULL,
	T2_Vehicle_Manufacturer VARCHAR(20) NOT NULL,
	T2_Vehicle_Engine_Number INTEGER NULL,
	T2_Vehicle_Chases_Number INTEGER NULL,
	T2_Number VARCHAR(20) NOT NULL,
	T2_Vehicle_Model_Number VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_VEHICLE PRIMARY KEY (T2_Vehicle_Id),
    CONSTRAINT T2_FK_VEHICLE FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id)
);

CREATE TABLE IF NOT EXISTS T2_CLAIM(
	T2_Claim_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Agreement_Id VARCHAR(20) NOT NULL,
	T2_Claim_Amount INTEGER NOT NULL,
	T2_Incident_Id VARCHAR(20) NOT NULL,
	T2_Damage_Type VARCHAR(20) NOT NULL,
	T2_Date_Of_Claim DATE NOT NULL,
	T2_Claim_Status VARCHAR(20) NOT NULL,
    CONSTRAINT T2_PK_CLAIM PRIMARY KEY(T2_Claim_Id),
    CONSTRAINT T2_FK_CLAIM FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id)
);

CREATE TABLE IF NOT EXISTS T2_CLAIM_SETTLEMENT(
	T2_Claim_Settlement_Id VARCHAR(20) NOT NULL,
	T2_Vehicle_Id VARCHAR(20) NOT NULL,
	T2_Date_Settled DATE NOT NULL,
	T2_Amount_Paid INTEGER NOT NULL,
	T2_Coverage_Id VARCHAR(20) NOT NULL,
	T2_Claim_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
    CONSTRAINT T2_PK_CLAIM_SETTLEMENT PRIMARY KEY(T2_Claim_Settlement_Id),
    CONSTRAINT T2_FK_CUST_CLAIM_SETTLEMENT FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_CLAIM_SETTLEMENT FOREIGN KEY (T2_Claim_Id) REFERENCES T2_CLAIM(T2_Claim_Id)
);

CREATE TABLE IF NOT EXISTS T2_INSURANCE_COMPANY(
	T2_Company_Name VARCHAR(20) NOT NULL, 
    T2_Company_Adress VARCHAR(20) NULL, 
	T2_Company_Contact_Number INTEGER NULL, 
    T2_Company_Fax INTEGER NULL, 
    T2_Company_Email VARCHAR(20) NULL, 
	T2_Company_Website VARCHAR(20) NULL, 
    T2_Company_Location VARCHAR(20) NULL, 
	T2_Company_Department_Name VARCHAR(20) NULL, 
    T2_Company_Office_Name VARCHAR(20) NULL,
	CONSTRAINT T2_PK_INSURANCE_COMPANY PRIMARY KEY (T2_Company_Name)
);

CREATE TABLE IF NOT EXISTS T2_STAFF(
	T2_Staff_Id VARCHAR(20) NOT NULL, 
	T2_Company_Name VARCHAR(20) NOT NULL,
	T2_Staff_Fname VARCHAR(10) NOT NULL,
	T2_Staff_LName VARCHAR(10) NOT NULL,
	T2_Staff_Address VARCHAR(20) NOT NULL,
	T2_Staff_Contact INTEGER NOT NULL,
	T2_Staff_Gender VARCHAR(2) NOT NULL,
	T2_Staff_Marital_Status VARCHAR(10) NULL,
	T2_Staff_Nationality VARCHAR(15) NULL,
	T2_Staff_Qualification VARCHAR(20) NULL,
	T2_Staff_Allowance INTEGER NULL ,
	T2_Staff_PPS_Number INTEGER NULL,
	CONSTRAINT T2_PK_STAFF PRIMARY KEY (T2_Staff_Id),
    CONSTRAINT T2_FK_STAFF FOREIGN KEY (T2_Company_Name) REFERENCES T2_INSURANCE_COMPANY(T2_Company_Name)
);

CREATE TABLE IF NOT EXISTS T2_DEPARTMENT(
	T2_Department_Name VARCHAR(20) NOT NULL, 
	T2_Company_Name VARCHAR(20) NOT NULL,
	T2_Office VARCHAR(18) NULL,
	T2_Contact_Information TEXT NOT NULL,
	T2_Department_Staff VARCHAR(18) NULL,
	T2_Department_Leader VARCHAR(18) NOT NULL,
	CONSTRAINT T2_PK_DEPARTMENT PRIMARY KEY (T2_Department_Name),
    CONSTRAINT T2_FK_DEPARTMENT FOREIGN KEY (T2_Company_Name) REFERENCES T2_INSURANCE_COMPANY(T2_Company_Name)
);

CREATE TABLE IF NOT EXISTS T2_OFFICE(
	T2_Office_Name VARCHAR(20) NOT NULL, 
	T2_Department_Name VARCHAR(20) NOT NULL,
	T2_Company_Name VARCHAR(20) NOT NULL,
	T2_Office_Leader VARCHAR(20) NOT NULL,
	T2_Contact_Information VARCHAR(20) NOT NULL,
	T2_Address VARCHAR(20) NOT NULL,
	T2_Admin_Cost INTEGER NOT NULL,
	T2_Staff VARCHAR(20) NOT NULL,
    CONSTRAINT T2_PK_OFFICE PRIMARY KEY(T2_Office_Name),
    CONSTRAINT T2_FK_COMP_OFFICE FOREIGN KEY (T2_Company_Name) REFERENCES T2_INSURANCE_COMPANY(T2_Company_Name),
    CONSTRAINT T2_FK_DEPT_OFFICE FOREIGN KEY (T2_Department_Name) REFERENCES T2_DEPARTMENT(T2_Department_Name)
);

CREATE TABLE IF NOT EXISTS T2_MEMBERSHIP(
	T2_Membership_Id VARCHAR(20) NOT NULL, 
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Membership_Type VARCHAR(18) NOT NULL,
	T2_Organisation_Contact VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_MEMBERSHIP PRIMARY KEY (T2_Membership_Id),
    CONSTRAINT T2_FK_MEMBERSHIP FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id)
);

CREATE TABLE IF NOT EXISTS T2_VEHICLE_SERVICE(
	T2_Vehicle_Service VARCHAR(20) NOT NULL, 
	T2_Vehicle_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Department_Name VARCHAR(20) NULL,
	T2_Vehicle_Service_Address VARCHAR(20) NOT NULL,
	T2_Vehicle_Service_Contact VARCHAR(20) NOT NULL,
	T2_Vehicle_Service_Incharge VARCHAR(20) NOT NULL,
	T2_Vehicle_Service_Type VARCHAR(20) NOT NULL,
    CONSTRAINT T2_PK_VEHICLE_SERVICE PRIMARY KEY(T2_Vehicle_Service),
    CONSTRAINT T2_FK_CUST_VEHICLE_SERVICE FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_VEHICLE_SERVICE FOREIGN KEY (T2_Vehicle_Id) REFERENCES T2_VEHICLE(T2_Vehicle_Id)
);

CREATE TABLE IF NOT EXISTS T2_COVERAGE(
	T2_Coverage_Id VARCHAR(20) NOT NULL, 
	T2_Company_Name VARCHAR(20) NOT NULL,
	T2_Coverage_Amount INTEGER NOT NULL,
	T2_Coverage_Type VARCHAR(10) NOT NULL,
	T2_Coverage_Level VARCHAR(15) NOT NULL,
	T2_Product_Id VARCHAR(20) NOT NULL,
	T2_Coverage_Description VARCHAR(100) NOT NULL,
	T2_Coverage_Terms VARCHAR(50) NOT NULL,
    CONSTRAINT T2_PK_COVERAGE PRIMARY KEY(T2_Coverage_Id),
    CONSTRAINT T2_FK_COVERAGE FOREIGN KEY (T2_Company_Name) REFERENCES T2_INSURANCE_COMPANY(T2_Company_Name)
);

CREATE TABLE IF NOT EXISTS T2_INSURANCE_POLICY_COVERAGE(
	T2_Agreement_Id VARCHAR(20) NOT NULL,
	T2_Coverage_Id VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_INSURANCE_POLICY_COVERAGE PRIMARY KEY (T2_Agreement_Id),
    CONSTRAINT T2_FK_INSURANCE_POLICY_COVERAGE FOREIGN KEY (T2_Coverage_Id) REFERENCES T2_COVERAGE(T2_Coverage_Id)
);

CREATE TABLE IF NOT EXISTS T2_NOK(
	T2_Nok_Id VARCHAR(20) NOT NULL, 
    T2_Nok_Name VARCHAR(20) NULL, 
    T2_Nok_Address VARCHAR(20) NULL, 
	T2_Nok_Phone_Number INTEGER NULL, 
    T2_Nok_Gender VARCHAR(2) NULL, 
    T2_Nok_Martial_Status VARCHAR(8) NULL, 
    T2_Agreement_Id VARCHAR(20) NOT NULL, 
    T2_Application_Id VARCHAR(20) NOT NULL, 
    T2_Cust_id VARCHAR(20) NOT NULL,
	CONSTRAINT T2_PK_NOK PRIMARY KEY (T2_Nok_Id),
    CONSTRAINT T2_CUST_FK_NOK FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_APP_FK_NOK FOREIGN KEY (T2_Application_Id) REFERENCES T2_APPLICATION(T2_Application_Id),
    CONSTRAINT T2_AGREE_FK_NOK FOREIGN KEY (T2_Agreement_Id) REFERENCES T2_INSURANCE_POLICY_COVERAGE(T2_Agreement_Id)
);

CREATE TABLE IF NOT EXISTS T2_POLICY_RENEWABLE(
	T2_Policy_Renewable_Id VARCHAR(20) NOT NULL, 
	T2_Date_Of_Renewal DATE NOT NULL, 
    T2_Type_Of_Renewal VARCHAR(15) NOT NULL,
    T2_Agreement_Id VARCHAR(20) NOT NULL,
	T2_Application_Id VARCHAR(20) NOT NULL, 
    T2_Cust_Id VARCHAR(20) NOT NULL, 
    CONSTRAINT T2_PK_POLICY_RENEWABLE PRIMARY KEY (T2_Policy_Renewable_Id),
    CONSTRAINT T2_FK_CUST_POLICY_RENEWABLE FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_APP_POLICY_RENEWABLE FOREIGN KEY (T2_Application_Id) REFERENCES T2_APPLICATION(T2_Application_Id),
	CONSTRAINT T2_FK_AGREE_POLICY_RENEWABLE FOREIGN KEY (T2_Agreement_Id) REFERENCES T2_INSURANCE_POLICY_COVERAGE(T2_Agreement_Id)
);

CREATE TABLE IF NOT EXISTS T2_INCIDENT(
	T2_Incident_Id VARCHAR(20) NOT NULL, 
    T2_Incident_Type VARCHAR(30) NULL, 
    T2_Incident_Date DATE NOT NULL,
	T2_Description VARCHAR(100) NULL, 
    CONSTRAINT T2_PK_INCIDENT PRIMARY KEY (T2_Incident_Id)
);

CREATE TABLE IF NOT EXISTS T2_INCIDENT_REPORT(
	T2_Incident_Report_Id VARCHAR(20) NOT NULL,
	T2_Incident_Id VARCHAR(20) NOT NULL, 
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Incident_Inspector VARCHAR(20) NOT NULL, 
	T2_Incident_Cost INTEGER NOT NULL,
	T2_Incident_Type CHAR(10) NOT NULL,
	T2_Incident_Report_Description VARCHAR(100) NOT NULL,
	CONSTRAINT T2_PK_INCIDENT_REPORT PRIMARY KEY(T2_Incident_Report_Id),
    CONSTRAINT T2_FK_CUST_INCIDENT_REPORT FOREIGN KEY (T2_Cust_Id) REFERENCES T2_CUSTOMER(T2_Cust_Id),
    CONSTRAINT T2_FK_INCIDENT_REPORT FOREIGN KEY (T2_Incident_Id) REFERENCES T2_INCIDENT(T2_Incident_Id)
);

CREATE TABLE IF NOT EXISTS T2_PRODUCT(
	T2_Product_Number VARCHAR(20) NOT NULL,
	T2_Company_Name VARCHAR(20) NOT NULL,
	T2_Product_Price INTEGER NULL,
	T2_Product_Type CHAR(15) NULL,
	CONSTRAINT T2_PK_PRODUCT PRIMARY KEY (T2_Product_Number),
    CONSTRAINT T2_FK_PRODUCT FOREIGN KEY (T2_Company_Name) REFERENCES T2_INSURANCE_COMPANY(T2_Company_Name)
);

CREATE TABLE IF NOT EXISTS T2_RECEIPT(
	T2_Receipt_Id VARCHAR(20) NOT NULL,
	T2_Premium_Payment_Id VARCHAR(20) NOT NULL,
	T2_Cust_Id VARCHAR(20) NOT NULL,
	T2_Cost INTEGER NOT NULL,
	T2_Time DATE NOT NULL,
	CONSTRAINT T2_PK_RECEIPT PRIMARY KEY (T2_Receipt_Id),
    CONSTRAINT T2_FK_RECEIPT FOREIGN KEY (T2_Premium_Payment_Id) REFERENCES T2_PREMIUM_PAYMENT(T2_Premium_Payment_Id)
);







